#!/usr/bin/env python

Import('env')


common_server = [\
    "os_psp.cpp",\
	"audio_driver_psp.cpp",\
	"rasterizer_psp.cpp",\
]

prog = env.add_program('#bin/godot_psp', ['godot_psp.cpp'] + common_server)

env.Command(
	"#bin/godot.elf", prog ,"psp-fixup-imports -o bin/godot.elf bin/godot_psp.psp.opt.32"
)

env.Command(
	"#bin/strip.elf", "#bin/godot.elf" ,"psp-strip bin/godot.elf -o bin/strip.elf"
)

env.Command(
	"#bin/EBOOT.PBP", "#bin/strip.elf" ,"pack-pbp bin/EBOOT.PBP bin/PARAM.SFO NULL          NULL NULL NULL          NULL  bin/strip.elf NULL"
)
