#!/usr/bin/env python

Import('env')


common_x11 = [
    "context_tgl.cpp",
    "crash_handler_x11.cpp",
    "os_x11.cpp",
    "key_mapping_x11.cpp",
    "joystick_linux.cpp",
]

prog = env.add_program('#bin/godot', ['godot_x11.cpp'] + common_x11)
